### ISSUE TITLE
Consider pinning `avr-hal` dependency revision

### ISSUE THREAD

**Issue by Rahix** [TVerse/boot-6502#3]
Hey!

Just wanted to let you know that you should probably pin the version of `avr-hal` to a specific git revision.  `avr-hal` is still quite early in development and newer versions might break your code so this way anyone trying to compile this project in the future will build against the same version of `avr-hal` that you originally worked with.

In practical terms, this means specifying the dependency in `Cargo.toml` like this:

```toml
[dependencies]
# panic-halt = "0.2.0"
arduino-mega2560 = { git = "https://github.com/Rahix/avr-hal", rev = "7337cd76cd96f2d27701b137396d94a06d3a501d" }
atmega2560-hal = { git = "https://github.com/Rahix/avr-hal", rev = "7337cd76cd96f2d27701b137396d94a06d3a501d" }
avr-hal-generic = { git = "https://github.com/Rahix/avr-hal", rev = "7337cd76cd96f2d27701b137396d94a06d3a501d" }
```

([`7337cd76cd96`](https://github.com/Rahix/avr-hal/commit/7337cd76cd96f2d27701b137396d94a06d3a501d) is the latest commit on master, you should probably check whether that still works for you and use an older one instead if it does not ...)

**Comment by TVerse** [comment]
Done! Thanks for the heads-up.
